### ISSUE TITLE
no module named charms

### ISSUE THREAD

**Issue by xtrusia** [mskalka/charm-cinder-three-par#1]
not sure this is right place to ask

I just tried to add relation cinder-three-par charm to existing cinder ( 3 cinders with HA )
on my test env.

and I got below error[1]

need to installl charms in code?

[1]
##

2018-05-31 09:33:36 DEBUG leader-settings-changed Traceback (most recent call last):
2018-05-31 09:33:36 DEBUG leader-settings-changed   File "/var/lib/juju/agents/unit-cinder-three-par-1/charm/hooks/leader-settings-changed", line 7, in <module>
2018-05-31 09:33:36 DEBUG leader-settings-changed     from charms.layer import basic
2018-05-31 09:33:36 DEBUG leader-settings-changed ImportError: No module named 'charms'
2018-05-31 09:33:36 ERROR juju.worker.uniter.operation runhook.go:113 hook "leader-settings-changed" failed: exit status 1
2018-05-31 09:33:42 DEBUG leader-settings-changed Traceback (most recent call last):
2018-05-31 09:33:42 DEBUG leader-settings-changed   File "/var/lib/juju/agents/unit-cinder-three-par-1/charm/hooks/leader-settings-changed", line 7, in <module>
2018-05-31 09:33:42 DEBUG leader-settings-changed     from charms.layer import basic
2018-05-31 09:33:42 DEBUG leader-settings-changed ImportError: No module named 'charms'
2018-05-31 09:33:42 ERROR juju.worker.uniter.operation runhook.go:113 hook "leader-settings-changed" failed: exit status 1
2018-05-31 09:33:52 DEBUG leader-settings-changed Traceback (most recent call last):
2018-05-31 09:33:52 DEBUG leader-settings-changed   File "/var/lib/juju/agents/unit-cinder-three-par-1/charm/hooks/leader-settings-changed", line 7, in <module>
2018-05-31 09:33:52 DEBUG leader-settings-changed     from charms.layer import basic
2018-05-31 09:33:52 DEBUG leader-settings-changed ImportError: No module named 'charms'
2018-05-31 09:33:52 ERROR juju.worker.uniter.operation runhook.go:113 hook "leader-settings-changed" failed: exit status 1
2018-05-31 09:34:17 DEBUG leader-settings-changed Traceback (most recent call last):
2018-05-31 09:34:17 DEBUG leader-settings-changed   File "/var/lib/juju/agents/unit-cinder-three-par-1/charm/hooks/leader-settings-changed", line 7, in <module>
2018-05-31 09:34:17 DEBUG leader-settings-changed     from charms.layer import basic
2018-05-31 09:34:17 DEBUG leader-settings-changed ImportError: No module named 'charms'
2018-05-31 09:34:17 ERROR juju.worker.uniter.operation runhook.go:113 hook "leader-settings-changed" failed: exit status 1
2018-05-31 09:34:58 DEBUG leader-settings-changed Traceback (most recent call last):
2018-05-31 09:34:58 DEBUG leader-settings-changed   File "/var/lib/juju/agents/unit-cinder-three-par-1/charm/hooks/leader-settings-changed", line 7, in <module>
2018-05-31 09:34:58 DEBUG leader-settings-changed     from charms.layer import basic
2018-05-31 09:34:58 DEBUG leader-settings-changed ImportError: No module named 'charms'
2018-05-31 09:34:58 ERROR juju.worker.uniter.operation runhook.go:113 hook "leader-settings-changed" failed: exit status 1

**Comment by xtrusia** [comment]
This issue is gone as leader something files removed
